### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by mohamad-supangat** [N0NamedGuy/opl-manager-next#1]
thanks in advance for your very interesting project
I using manjaro 19.0.0 x86_64 
with npm 6.13.4 and yarn 1.21.1

it alway show this error during npm start or yarn start
![image](https://user-images.githubusercontent.com/48933993/74914586-46e92980-53f5-11ea-90c5-f54dcec29ca1.png)

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at noopServiceWorkerMiddleware (/home/deve/tmp/opl-manager-next/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/deve/tmp/opl-manager-next/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deve/tmp/opl-manager-next/node_modules/express/lib/router/index.js:317:13)
    at /home/deve/tmp/opl-manager-next/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/deve/tmp/opl-manager-next/node_modules/express/lib/router/index.js:335:12)
    at next (/home/deve/tmp/opl-manager-next/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/deve/tmp/opl-manager-next/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/deve/tmp/opl-manager-next/node_modules/express/lib/router/layer.js:95:5)

**Comment by N0NamedGuy** [comment]
Thank for your report. Right now I haven't had enough time to develop this project further, so I will update you whenever I can.
